version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: moshe
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
# psql -h localhost -p 5432 -d demo -U moshe
#  pgadmin:
#    image: dpage/pgadmin4:latest
#    restart: always
#    ports:
#      - 5050:80
#    environment:
#      PGADMIN_DEFAULT_EMAIL: moshiksar@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: password
#    depends_on:
#      - postgres
